version: '3'
services:
    apache-php:
        build:
            context: .
            dockerfile: ./apache/Dockerfile
        image: aleksa/php:7.2.14-apache
        networks:
            - backend
        depends_on:
            - db
        volumes:
            - ../../Source/apache:/var/www
        ports:
            - "80:80"
            - "443:443"
    db:
        build:
            context: .
            dockerfile: ./mariadb/Dockerfile
        image: aleksa/mariadb:10.3.9
        restart: always
        networks:
            - backend
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
networks:
    backend:
